FROM docker.io/library/ubuntu:jammy-20230126

WORKDIR /etc/configs

COPY ubuntu_22/install_basic_utils.sh ./
RUN ./install_basic_utils.sh

COPY ubuntu_22/install_gcc.sh ./
RUN ./install_gcc.sh

COPY ubuntu_22/install_llvm.sh ./
RUN ./install_llvm.sh

COPY ubuntu_22/install_gnu_tools.sh ./
RUN ./install_gnu_tools.sh

COPY ubuntu_22/install_valgrind.sh ./
RUN ./install_valgrind.sh

COPY ubuntu_22/install_cmake.sh ./
RUN ./install_cmake.sh

COPY ubuntu_22/install_vcpkg.sh ./
RUN ./install_vcpkg.sh
ENV VCPKG_INSTALLATION_ROOT "/usr/local/vcpkg"

COPY ubuntu_22/install_python.sh ./
RUN ./install_python.sh

COPY ubuntu_22/install_nodejs.sh ./
RUN ./install_nodejs.sh

COPY ubuntu_22/config_system.sh ./
RUN ./config_system.sh

COPY license.md ./

WORKDIR /root

# See https://github.com/opencontainers/image-spec/blob/main/annotations.md
LABEL org.opencontainers.image.authors="Nikita Rudenko"
LABEL org.opencontainers.image.vendor="Nikita Rudenko"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.title="Container image for C++ builds."
LABEL org.opencontainers.image.base.name="ubuntu:22.04"
